# DEEL 1: Installeer de benodigde software op de server zelf (localhost)
- name: Prepareer de Control Node (Semaphore)
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Installeer Paramiko Python Library
      ansible.builtin.command: pip install paramiko
      changed_when: false

# DEEL 2: Configureer de Routers
- name: SASE Lab Basis Setup
  hosts: all
  gather_facts: no
  connection: network_cli # Dit is belangrijk voor VyOS!
  tasks:
    - name: Haal router feiten op
      vyos.vyos.vyos_facts:
        gather_subset: min

    - name: Toon succesbericht
      debug:
        msg: "Verbonden met {{ ansible_net_hostname }}! Versie: {{ ansible_net_version }}"
