- name: Configureer SASE WireGuard Tunnel (VyOS 1.4/1.5 Syntax)
  hosts: all
  gather_facts: no
  connection: network_cli
  vars:
    # --- JOUW VARIABELEN (Vul deze weer in!) ---
    hq_wan_ip: "10.0.0.1" 
    branch_wan_ip: "10.0.0.2"

    hq_private_key: "ePwQd9Fw45z8yIkFAAAtDuhfeBvzy/Ennj9vFdtXMHU="
    hq_public_key: "ik0dZqlozE2l7uZenGmoKUHkk0kOU8niFX8wJGneoGU="
    
    branch_private_key: "ULEH12xf4SE2bxaz+IG+5sC1ScrJnKVFynf5NGhmQkE="
    branch_public_key: "OCdS9/QtytdYt5u1PDIH9YLj8cDdm0F1ZcwK5wEvJUo="

  tasks:
    # --- HQ ROUTER CONFIGURATIE ---
    - name: Setup WireGuard op HQ
      vyos.vyos.vyos_config:
        lines:
          - set interfaces wireguard wg0 address '10.100.0.1/30'
          - set interfaces wireguard wg0 port '51820'
          - set interfaces wireguard wg0 private-key '{{ hq_private_key }}'
          # Nieuwe syntax: Peer configuratie
          - set interfaces wireguard wg0 peer branch-office allowed-ips '10.100.0.2/32'
          - set interfaces wireguard wg0 peer branch-office public-key '{{ branch_public_key }}'
      when: inventory_hostname == 'hq-router'

    # --- BRANCH ROUTER CONFIGURATIE ---
    - name: Setup WireGuard op Branch
      vyos.vyos.vyos_config:
        lines:
          - set interfaces wireguard wg0 address '10.100.0.2/30'
          - set interfaces wireguard wg0 private-key '{{ branch_private_key }}'
          # Nieuwe syntax: Endpoint gesplitst
          - set interfaces wireguard wg0 peer hq-office allowed-ips '10.100.0.1/32'
          - set interfaces wireguard wg0 peer hq-office address '{{ hq_wan_ip }}'
          - set interfaces wireguard wg0 peer hq-office port '51820'
          - set interfaces wireguard wg0 peer hq-office public-key '{{ hq_public_key }}'
          - set interfaces wireguard wg0 peer hq-office persistent-keepalive '15'
      when: inventory_hostname == 'branch-router'

    # --- FIREWALL OPENZETTEN (VOEG DIT TOE) ---
    
    # 1. Maak de firewall regel aan
    - name: Configureer Firewall Regel voor WireGuard
      vyos.vyos.vyos_config:
        lines:
          - set firewall name WAN-IN default-action 'drop'
          - set firewall name WAN-IN rule 10 action 'accept'
          - set firewall name WAN-IN rule 10 protocol 'udp'
          - set firewall name WAN-IN rule 10 destination port '51820'
          - set firewall name WAN-IN rule 10 description 'Allow WireGuard'
          # Sta ook pings toe (handig voor debuggen)
          - set firewall name WAN-IN rule 20 action 'accept'
          - set firewall name WAN-IN rule 20 protocol 'icmp'

    # 2. Koppel de firewall aan de WAN interface (eth1)
    # LET OP: Check of jouw WAN interface eth1 is!
    - name: Koppel Firewall aan Interface
      vyos.vyos.vyos_config:
        lines:
          - set interfaces ethernet eth1 firewall local name 'WAN-IN'
